[package]
name = "pico2w"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = ["ism330dhcx-driver", "imu-producer-interrupt-executor"]
imu-400hz = []
ism330dhcx-driver = ["dep:ism330dhcx-rs", "rp2350_platform/ism330dhcx-driver"]
imu-odr-1666hz = ["ism330dhcx-driver"]
ism330dhcx-1k666 = ["imu-odr-1666hz"]
scope-timing-pins = ["veloxity_core/scope-timing-pins"]
imu-producer-scope = ["scope-timing-pins"]
pre-control-scope = ["scope-timing-pins", "veloxity_core/pre-control-scope"]
rc-command-scope = ["scope-timing-pins", "veloxity_core/rc-command-scope"]
imu-producer-interrupt-executor = []
core1-disable-heartbeat = []
core1-disable-mavlink-tx = []
core1-disable-mavlink-rx = []
core1-disable-crsf = []
core1-disable-gps = []
control-scope-estimator = ["veloxity_core/control-scope-estimator"]
control-scope-controller = ["veloxity_core/control-scope-controller"]
control-scope-mixer = ["veloxity_core/control-scope-mixer"]
control-scope-pwm = ["veloxity_core/control-scope-pwm"]

[dependencies]
rp2350_platform = { workspace = true }
veloxity_core = { workspace = true }
veloxity_mavlink = { workspace = true }

cortex-m = "0.7.7"
cortex-m-rt = { version = "0.7.0" }
crsf = "2.0.1"
critical-section = "1.2.0"
embassy-executor = { version = "0.10.0" }
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embedded-hal-nb = "1.0.0"
fixed = "1.31.0"
heapless = { version = "0.8.0", default-features = false }
ism330dhcx-rs = { version = "2.0.0", default-features = false, features = ["async"], optional = true }
nb = "1.1.0"
panic-halt = "1.0.0"
pio = "0.3.0"
static_cell = "2.1"

[lints]
workspace = true

[[bin]]
name = "veloxity"
test = false
bench = false
