[package]
name = "veloxity_mavlink"
version = "0.1.0"
edition = "2024"

[dependencies]
veloxity_core = { workspace = true }
mavio = { version = "0.5.5", default-features = false, features = [
  "embedded-io",
] }
mavspec = { version = "0.6.4", default-features = false, features = ["rust"] }

[build-dependencies]
mavspec = { version = "0.6.4", features = ["rust_gen"] }

[lints]
workspace = true
