[package]
name = "pixracerpro"
version = "0.1.0"
edition = "2024"

[dependencies]
stm_32 = { workspace = true }
voloxide_core = { workspace = true }
voloxide_mavlink = { workspace = true }

# # for debugging stm32 devices:
# defmt = { version = "0.3" }

panic-halt = "1.0.0"

[lints]
workspace = true

[[bin]]
name = "voloxide"
test = false
bench = false
