[build]
target = "thumbv7em-none-eabihf"

# Now, add your target-specific settings
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H743IIK6"
rustflags = [
  "-C",
  "linker=rust-lld",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
]

# Environment variables are also applied correctly from this file
[env]
DEFMT_LOG = "debug"
