[package]
name = "voloxide_core"
version = "0.1.0"
edition = "2024"

[dependencies]
# bitflags = "2.6.0"
bitflags = { version = "2.6.0", default-features = false}
micro_algebra = { git = "ssh://git@github.com/magicc-safety/micro_algebra.git", branch = "main" }
#micro_algebra = { version = "0.1.0", path = "../../micro_algebra" }

# For .sqrt(), .powf() and .powi() traits for f64s
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
libm = "0.2"

# Mavlink stuff
mavio = { version = "0.5.5", default-features = false, features = [
  "embedded-io",
] }
mavspec = { version = "0.6.4", default-features = false, features = ["rust"] }

# for debugging stm32 devices:
# defmt = { version = "0.3" }

# For safe logging mutex:
critical-section = { version = "1.2.0" }

# for testing the estimator
[dev-dependencies]
csv = { version = "1.3.1"}
serde = { version = "1.0.225", features = ["derive"] }
critical-section = { version = "1.2.0", features = ["std"] }

[build-dependencies]
mavspec = { version = "0.6.4", features = ["rust_gen"] }

[lints]
workspace = true
